import { NextResponse } from 'next/server';
import { getJwkSet } from '@/lib/auth/jwks';

/**
 * JWKS endpoint exposes signing keys for the Rust API. Keys are cached in-memory
 * for efficiency but regenerated by NextAuth when necessary.
 */
export async function GET() {
  const jwks = await getJwkSet();
  return NextResponse.json(jwks);
}
