name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install web dependencies
        working-directory: apps/web
        run: pnpm install --frozen-lockfile

      - name: Build web
        working-directory: apps/web
        run: pnpm run build

      - name: Build API
        working-directory: apps/api
        run: cargo build --locked

      - name: Run API tests
        working-directory: apps/api
        run: cargo test --locked

      - name: Run web tests
        working-directory: apps/web
        run: pnpm run test -- --watch=false
