version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-foodies}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log debug file:/data/database.db
    environment:
      SURREALDB_USER: root
      SURREALDB_PASS: root
    ports:
      - '8000:8000'
    volumes:
      - surrealdb-data:/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data

  nats:
    image: nats:2
    command: ['-js']
    ports:
      - '4222:4222'
      - '8222:8222'

volumes:
  postgres-data:
  surrealdb-data:
  minio-data:
